<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
          ['Afghanistan','Kabul','easy', 'https://en.wikipedia.org/wiki/Afghanistan'],
          ['Albania','Tirana','moderate','https://en.wikipedia.org/wiki/Albania'],
          ['Algeria','Algiers','easy','https://en.wikipedia.org/wiki/Algeria'],
          ['American Samoa','Pago Pago','hard','https://en.wikipedia.org/wiki/American_Samoa'],
          ['Andorra','Andorra la Vella','hard','https://en.wikipedia.org/wiki/Andorra'],
          ['Angola','Luanda','easy','https://en.wikipedia.org/wiki/Angola'],
          ['Anguilla','The Valley','hard','https://en.wikipedia.org/wiki/Anguilla'],
          ['Antigua and Barbuda',"St. John's",'hard','https://en.wikipedia.org/wiki/Antigua_and_Barbuda'],
          ['Argentina','Buenos Aires','easy','https://en.wikipedia.org/wiki/Argentina'],
          ['Armenia','Yerevan','easy','https://en.wikipedia.org/wiki/Armenia'],
          ['Aruba','Oranjestad','hard','https://en.wikipedia.org/wiki/Aruba'],
          ['Australia','Canberra','moderate','https://en.wikipedia.org/wiki/Australia'],
          ['Austria','Vienna','easy','https://en.wikipedia.org/wiki/Austria'],
          ['Azerbaijan','Baku','easy','https://en.wikipedia.org/wiki/Azerbaijan'],
          ['Bahamas','Nassau','moderate','https://en.wikipedia.org/wiki/Bahamas'],
          ['Bahrain','Manama','hard','https://en.wikipedia.org/wiki/Bahrain'],
          ['Bangladesh','Dhaka','easy','https://en.wikipedia.org/wiki/Bangladesh'],
          ['Barbados','Bridgetown','hard','https://en.wikipedia.org/wiki/Barbados'],
          ['Belarus','Minsk','easy','https://en.wikipedia.org/wiki/Belarus'],
          ['Belgium','Brussels','easy','https://en.wikipedia.org/wiki/Belgium'],
          ['Belize','Belmopan','hard','https://en.wikipedia.org/wiki/Belize'],
          ['Benin','Porto-Novo','moderate','https://en.wikipedia.org/wiki/Benin'],
          ['Bermuda','Hamilton','hard','https://en.wikipedia.org/wiki/Bermuda'],
          ['Bhutan','Thimphu','hard','https://en.wikipedia.org/wiki/Bhutan'],
          ['Bolivia','Sucre','moderate','https://en.wikipedia.org/wiki/Bolivia'],
          ['Bosnia and Herzegovina','Sarajevo','moderate','https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina'],
          ['Botswana','Gaborone','moderate','https://en.wikipedia.org/wiki/Botswana'],
          ['Brazil','Brasília','easy','https://en.wikipedia.org/wiki/Brazil'],
          ['British Virgin Islands','Road Town','hard','https://en.wikipedia.org/wiki/British_Virgin_Islands'],
          ['Brunei','Bandar Seri Begawan','hard','https://en.wikipedia.org/wiki/Brunei'],
          ['Bulgaria','Sofia','easy','https://en.wikipedia.org/wiki/Bulgaria'],
          ['Burkina Faso','Ouagadougou','moderate','https://en.wikipedia.org/wiki/Burkina_Faso'],
          ['Burma','Yangon','easy','https://en.wikipedia.org/wiki/Burma'],
          ['Burundi','Bujumbura','moderate','https://en.wikipedia.org/wiki/Burundi'],
          ['Cambodia','Phnom Penh','easy','https://en.wikipedia.org/wiki/Cambodia'],
          ['Cameroon','Yaoundé','moderate','https://en.wikipedia.org/wiki/Cameroon'],
          ['Canada','Ottawa','moderate','https://en.wikipedia.org/wiki/Canada'],
          ['Cape Verde','Praia','hard','https://en.wikipedia.org/wiki/Cape_Verde'],
          ['Cayman Islands','George Town','hard','https://en.wikipedia.org/wiki/Cayman_Islands'],
          ['Central African Republic','Bangui','moderate','https://en.wikipedia.org/wiki/Central_African_Republic'],
          ['Chad',"N'Djamena",'moderate','https://en.wikipedia.org/wiki/Chad'],
          ['Chile','Santiago','easy','https://en.wikipedia.org/wiki/Chile'],
          ['China','Beijing','easy','https://en.wikipedia.org/wiki/China'],
          ['Christmas Island','Flying Fish Cove','hard','https://en.wikipedia.org/wiki/Christmas_Island'],
          ['Cocos (Keeling) Islands','West Island','hard','https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands'],
          ['Colombia','Bogotá','easy','https://en.wikipedia.org/wiki/Colombia'],
          ['Comoros','Moroni','hard','https://en.wikipedia.org/wiki/Comoros'],
          ['Cook Islands','Avarua','hard','https://en.wikipedia.org/wiki/Cook_Islands'],
          ['Costa Rica','San José','moderate','https://en.wikipedia.org/wiki/Costa_Rica'],
          ['Croatia','Zagreb','moderate','https://en.wikipedia.org/wiki/Croatia'],
          ['Cuba','Havana','easy','https://en.wikipedia.org/wiki/Cuba'],
          ['Curaçao','Willemstad','hard','https://en.wikipedia.org/wiki/Curaçao'],
          ['Cyprus','Nicosia','moderate','https://en.wikipedia.org/wiki/Cyprus'],
          ['Czech Republic','Prague','easy','https://en.wikipedia.org/wiki/Czech_Republic'],
          ["Cote d'Ivoire",'Yamoussoukro','moderate','https://en.wikipedia.org/wiki/Ivory_Coast'],
          ['Dem. Rep. of the Congo','Kinshasa','easy','https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'],
          ['Denmark','Copenhagen','easy','https://en.wikipedia.org/wiki/Denmark'],
          ['Dhekelia','Episkopi Cantonment','hard','https://en.wikipedia.org/wiki/Dhekelia'],
          ['Djibouti','Djibouti','moderate','https://en.wikipedia.org/wiki/Djibouti'],
          ['Dominica','Roseau','hard','https://en.wikipedia.org/wiki/Dominica'],
          ['Dominican Republic','Santo Domingo','easy','https://en.wikipedia.org/wiki/Dominican_Republic'],
          ['East Timor','Dili','moderate','https://en.wikipedia.org/wiki/East_Timor'],
          ['Ecuador','Quito','easy','https://en.wikipedia.org/wiki/Ecuador'],
          ['Egypt','Cairo','easy','https://en.wikipedia.org/wiki/Egypt'],
          ['El Salvador','San Salvador','moderate','https://en.wikipedia.org/wiki/El_Salvador'],
          ['Eritrea','Asmara','moderate','https://en.wikipedia.org/wiki/Eritrea'],
          ['Estonia','Tallinn','moderate','https://en.wikipedia.org/wiki/Estonia'],
          ['Ethiopia','Addis Ababa','easy','https://en.wikipedia.org/wiki/Ethiopia'],
          ['Falkland Islands','Stanley','hard','https://en.wikipedia.org/wiki/Falkland_Islands'],
          ['Faroe Islands','Tórshavn','hard','https://en.wikipedia.org/wiki/Faroe_Islands'],
          ['Micronesia','Palikir','hard','https://en.wikipedia.org/wiki/Micronesia'],
          ['Fiji','Suva','hard','https://en.wikipedia.org/wiki/Fiji'],
          ['Finland','Helsinki','moderate','https://en.wikipedia.org/wiki/Finland'],
          ['France','Paris','easy','https://en.wikipedia.org/wiki/France'],
          ['French Guiana','Cayenne','hard','https://en.wikipedia.org/wiki/French_Guiana'],
          ['French Polynesia','Papeete','hard','https://en.wikipedia.org/wiki/French_Polynesia'],
          ['Gabon','Libreville','moderate','https://en.wikipedia.org/wiki/Gabon'],
          ['Gambia','Banjul','hard','https://en.wikipedia.org/wiki/Gambia'],
          ['Georgia','Tbilisi','moderate','https://en.wikipedia.org/wiki/Georgia'],
          ['Germany','Berlin','easy','https://en.wikipedia.org/wiki/Germany'],
          ['Ghana','Accra','easy','https://en.wikipedia.org/wiki/Ghana'],
          ['Gibraltar','Gibraltar','hard','https://en.wikipedia.org/wiki/Gibraltar'],
          ['Greece','Athens','moderate','https://en.wikipedia.org/wiki/Greece'],
          ['Greenland','Nuuk','hard','https://en.wikipedia.org/wiki/Greenland'],
          ['Grenada',"St. George's",'hard','https://en.wikipedia.org/wiki/Grenada'],
          ['Guam','Hagåtña','hard','https://en.wikipedia.org/wiki/Guam'],
          ['Guatemala','Guatemala City','easy','https://en.wikipedia.org/wiki/Guatemala'],
          ['Guernsey','St. Peter Port','hard','https://en.wikipedia.org/wiki/Guernsey'],
          ['Guinea','Conakry','easy','https://en.wikipedia.org/wiki/Guinea'],
          ['Guinea-Bissau','Bissau','moderate','https://en.wikipedia.org/wiki/Guinea-Bissau'],
          ['Guyana','Georgetown','hard','https://en.wikipedia.org/wiki/Guyana'],
          ['Haiti','Port-au-Prince','easy','https://en.wikipedia.org/wiki/Haiti'],
          ['Holy See','Vatican City','hard','https://en.wikipedia.org/wiki/Holy_See'],
          ['Honduras','Tegucigalpa','moderate','https://en.wikipedia.org/wiki/Honduras'],
          ['Hungary','Budapest','easy','https://en.wikipedia.org/wiki/Hungary'],
          ['Iceland','Reykjavík','hard','https://en.wikipedia.org/wiki/Iceland'],
          ['India','New Delhi','moderate','https://en.wikipedia.org/wiki/India'],
          ['Indonesia','Jakarta','easy','https://en.wikipedia.org/wiki/Indonesia'],
          ['Iran','Tehran','easy','https://en.wikipedia.org/wiki/Iran'],
          ['Iraq','Baghdad','easy','https://en.wikipedia.org/wiki/Iraq'],
          ['Ireland','Dublin','moderate','https://en.wikipedia.org/wiki/Ireland'],
          ['Isle of Man','Douglas','hard','https://en.wikipedia.org/wiki/Isle_of_Man'],
          ['Israel','Jerusalem','moderate','https://en.wikipedia.org/wiki/Israel'],
          ['Italy','Rome','easy','https://en.wikipedia.org/wiki/Italy'],
          ['Jamaica','Kingston','moderate','https://en.wikipedia.org/wiki/Jamaica'],
          ['Japan','Tokyo','easy','https://en.wikipedia.org/wiki/Japan'],
          ['Jersey','St. Helier','hard','https://en.wikipedia.org/wiki/Jersey'],
          ['Jordan','Amman','easy','https://en.wikipedia.org/wiki/Jordan'],
          ['Kazakhstan','Astana','moderate','https://en.wikipedia.org/wiki/Kazakhstan'],
          ['Kenya','Nairobi','easy','https://en.wikipedia.org/wiki/Kenya'],
          ['Kiribati','Tarawa','hard','https://en.wikipedia.org/wiki/Kiribati'],
          ['Kosovo','Pristina','moderate','https://en.wikipedia.org/wiki/Kosovo'],
          ['Kuwait','Kuwait City','easy','https://en.wikipedia.org/wiki/Kuwait'],
          ['Kyrgyzstan','Bishkek','moderate','https://en.wikipedia.org/wiki/Kyrgyzstan'],
          ['Laos','Vientiane','moderate','https://en.wikipedia.org/wiki/Laos'],
          ['Latvia','Riga','moderate','https://en.wikipedia.org/wiki/Latvia'],
          ['Lebanon','Beirut','easy','https://en.wikipedia.org/wiki/Lebanon'],
          ['Lesotho','Maseru','moderate','https://en.wikipedia.org/wiki/Lesotho'],
          ['Liberia','Monrovia','moderate','https://en.wikipedia.org/wiki/Liberia'],
          ['Libya','Tripoli','easy','https://en.wikipedia.org/wiki/Libya'],
          ['Liechtenstein','Vaduz','hard','https://en.wikipedia.org/wiki/Liechtenstein'],
          ['Lithuania','Vilnius','moderate','https://en.wikipedia.org/wiki/Lithuania'],
          ['Luxembourg','Luxembourg','hard','https://en.wikipedia.org/wiki/Luxembourg'],
          ['Macedonia','Skopje','moderate','https://en.wikipedia.org/wiki/Macedonia'],
          ['Madagascar','Antananarivo','easy','https://en.wikipedia.org/wiki/Madagascar'],
          ['Malawi','Lilongwe','moderate','https://en.wikipedia.org/wiki/Malawi'],
          ['Malaysia','Kuala Lumpur','easy','https://en.wikipedia.org/wiki/Malaysia'],
          ['Maldives','Malé','hard','https://en.wikipedia.org/wiki/Maldives'],
          ['Mali','Bamako','easy','https://en.wikipedia.org/wiki/Mali'],
          ['Malta','Valletta','hard','https://en.wikipedia.org/wiki/Malta'],
          ['Marshall Islands','Majuro','hard','https://en.wikipedia.org/wiki/Marshall_Island'],
          ['Mauritania','Nouakchott','moderate','https://en.wikipedia.org/wiki/Mauritania'],
          ['Mauritius','Port Louis','moderate','https://en.wikipedia.org/wiki/Mauritius'],
          ['Mexico','Mexico City','easy','https://en.wikipedia.org/wiki/Mexico'],
          ['Moldova','Chisinau','moderate','https://en.wikipedia.org/wiki/Moldova'],
          ['Monaco','Monaco','hard','https://en.wikipedia.org/wiki/Monaco'],
          ['Mongolia','Ulaanbaatar','moderate','https://en.wikipedia.org/wiki/Mongolia'],
          ['Montenegro','Podgorica','moderate','https://en.wikipedia.org/wiki/Montenegro'],
          ['Montserrat','Plymouth','hard','https://en.wikipedia.org/wiki/Montserrat'],
          ['Morocco','Rabat','easy','https://en.wikipedia.org/wiki/Morocco'],
          ['Mozambique','Maputo','moderate','https://en.wikipedia.org/wiki/Mozambique'],
          ['Namibia','Windhoek','moderate','https://en.wikipedia.org/wiki/Namibia'],
          ['Nauru','Yaren','hard','https://en.wikipedia.org/wiki/Nauru'],
          ['Nepal','Kathmandu','moderate','https://en.wikipedia.org/wiki/Nepal'],
          ['Netherlands','Amsterdam','moderate','https://en.wikipedia.org/wiki/Netherlands'],
          ['New Caledonia','Nouméa','hard','https://en.wikipedia.org/wiki/New_Caledonia'],
          ['New Zealand','Wellington','moderate','https://en.wikipedia.org/wiki/New_Zealand'],
          ['Nicaragua','Managua','moderate','https://en.wikipedia.org/wiki/Nicaragua'],
          ['Niger','Niamey','moderate','https://en.wikipedia.org/wiki/Niger'],
          ['Nigeria','Abuja','moderate','https://en.wikipedia.org/wiki/Nigeria'],
          ['Niue','Alofi','hard','https://en.wikipedia.org/wiki/Niue'],
          ['Norfolk Island','Kingston','hard','https://en.wikipedia.org/wiki/Norfolk_Island'],
          ['North Korea','Pyongyang','easy','https://en.wikipedia.org/wiki/North_Korea'],
          ['Cyprus','Nicosia','hard','https://en.wikipedia.org/wiki/Cyprus'],
          ['Northern Ireland','Belfast','hard','https://en.wikipedia.org/wiki/Northern_Ireland'],
          ['Northern Mariana Islands','Saipan','hard','https://en.wikipedia.org/wiki/Northern_Mariana_Islands'],
          ['Norway','Oslo','moderate','https://en.wikipedia.org/wiki/Norway'],
          ['Oman','Muscat','moderate','https://en.wikipedia.org/wiki/Oman'],
          ['Pakistan','Islamabad','moderate','https://en.wikipedia.org/wiki/Pakistan'],
          ['Palau','Ngerulmud','hard','https://en.wikipedia.org/wiki/Palau'],
          ['Palestine','Jerusalem','hard','https://en.wikipedia.org/wiki/Palestine'],
          ['Panama','Panama City','moderate','https://en.wikipedia.org/wiki/Panama'],
          ['Papua New Guinea','Port Moresby','moderate','https://en.wikipedia.org/wiki/Papua_New_Guinea'],
          ['Paraguay','Asunción','moderate','https://en.wikipedia.org/wiki/Paraguay'],
          ['Peru','Lima','easy','https://en.wikipedia.org/wiki/Peru'],
          ['Philippines','Manila','easy','https://en.wikipedia.org/wiki/Philippines'],
          ['Pitcairn Islands','Adamstown','hard','https://en.wikipedia.org/wiki/Pitcairn_Islands'],
          ['Poland','Warsaw','easy','https://en.wikipedia.org/wiki/Poland'],
          ['Portugal','Lisbon','moderate','https://en.wikipedia.org/wiki/Portugal'],
          ['Puerto Rico','San Juan','moderate','https://en.wikipedia.org/wiki/Puerto_Rico'],
          ['Qatar','Doha','easy','https://en.wikipedia.org/wiki/Qatar'],
          ['Taiwan','Taipei','easy','https://en.wikipedia.org/wiki/Taiwan'],
          ['Republic of the Congo','Brazzaville','easy','https://en.wikipedia.org/wiki/Republic_of_the_Congo'],
          ['Romania','Bucharest','easy','https://en.wikipedia.org/wiki/Romania'],
          ['Russia','Moscow','easy','https://en.wikipedia.org/wiki/Russia'],
          ['Rwanda','Kigali','moderate','https://en.wikipedia.org/wiki/Rwanda'],
          ['Saint Barthélemy','Gustavia','hard','https://en.wikipedia.org/wiki/Saint_Barthélemy'],
          ['Saint Helena','Jamestown','hard','https://en.wikipedia.org/wiki/Saint_Helena'],
          ['Saint Kitts and Nevis','Basseterre','hard','https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis'],
          ['Saint Lucia','Castries','hard','https://en.wikipedia.org/wiki/Saint_Lucia'],
          ['Saint Martin','Marigot','hard','https://en.wikipedia.org/wiki/Saint_Martin'],
          ['Saint Pierre and Miquelon','St. Pierre','hard','https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon'],
          ['St. Vincent and the Grenadines','Kingstown','hard','https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines'],
          ['Samoa','Apia','hard','https://en.wikipedia.org/wiki/Samoa'],
          ['San Marino','San Marino','hard','https://en.wikipedia.org/wiki/San_Marino'],
          ['Saudi Arabia','Riyadh','easy','https://en.wikipedia.org/wiki/Saudi_Arabia'],
          ['Scotland','Edinburgh','moderate','https://en.wikipedia.org/wiki/Scotland'],
          ['Senegal','Dakar','moderate','https://en.wikipedia.org/wiki/Senegal'],
          ['Serbia','Belgrade','easy','https://en.wikipedia.org/wiki/Serbia'],
          ['Seychelles','Victoria','hard','https://en.wikipedia.org/wiki/Seychelles'],
          ['Sierra Leone','Freetown','moderate','https://en.wikipedia.org/wiki/Sierra_Leone'],
          ['Singapore','Singapore','easy','https://en.wikipedia.org/wiki/Singapore'],
          ['Sint Maarten','Philipsburg','hard','https://en.wikipedia.org/wiki/Sint_Maarten'],
          ['Slovakia','Bratislava','moderate','https://en.wikipedia.org/wiki/Slovakia'],
          ['Slovenia','Ljubljana','moderate','https://en.wikipedia.org/wiki/Slovenia'],
          ['Solomon Islands','Honiara','hard','https://en.wikipedia.org/wiki/Solomon_Islands'],
          ['Somalia','Mogadishu','easy','https://en.wikipedia.org/wiki/Somalia'],
          ['Somaliland','Hargeisa','hard','https://en.wikipedia.org/wiki/Somaliland'],
          ['South Africa','Pretoria','easy','https://en.wikipedia.org/wiki/South_Africa'],
          ['S. Georgia and S. Sandwich Islands','King Edwward Point','hard','https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands'],
          ['South Korea','Seoul','easy','https://en.wikipedia.org/wiki/South_Korea'],
          ['South Ossetia','Tskhinvali','hard','https://en.wikipedia.org/wiki/South_Ossetia'],
          ['South Sudan','Juba','moderate','https://en.wikipedia.org/wiki/South_Sudan'],
          ['Spain','Madrid','easy','https://en.wikipedia.org/wiki/Spain'],
          ['Sri Lanka','Sri Jayawardenapura Kotte','hard','https://en.wikipedia.org/wiki/Sri_Lanka'],
          ['Sudan','Khartoum','easy','https://en.wikipedia.org/wiki/Sudan'],
          ['Suriname','Paramaribo','moderate','https://en.wikipedia.org/wiki/Suriname'],
          ['Swaziland','Mbabane','hard','https://en.wikipedia.org/wiki/Swaziland'],
          ['Sweden','Stockholm','moderate','https://en.wikipedia.org/wiki/Sweden'],
          ['Switzerland','Bern','hard','https://en.wikipedia.org/wiki/Switzerland'],
          ['Syria','Damascus','easy','https://en.wikipedia.org/wiki/Syria'],
          ['São Tomé and Príncipe','São Tomé','hard','https://en.wikipedia.org/wiki/São_Tomé_and_Príncipe'],
          ['Tajikistan','Dushanbe','moderate','https://en.wikipedia.org/wiki/Tajikistan'],
          ['Tanzania','Dodoma','moderate','https://en.wikipedia.org/wiki/Tanzania'],
          ['Thailand','Bangkok','easy','https://en.wikipedia.org/wiki/Thailand'],
          ['Togo','Lomé','moderate','https://en.wikipedia.org/wiki/Togo'],
          ['Tonga','Nukuʻalofa','hard','https://en.wikipedia.org/wiki/Tonga'],
          ['Transnistria','Tiraspol','moderate','https://en.wikipedia.org/wiki/Transnistria'],
          ['Trinidad and Tobago','Port of Spain','hard','https://en.wikipedia.org/wiki/Trinidad_and_Tobago'],
          ['Tristan da Cunha','Edinburgh of the Seven Seas','hard','https://en.wikipedia.org/wiki/Tristan_da_Cunha'],
          ['Tunisia','Tunis','moderate','https://en.wikipedia.org/wiki/Tunisia'],
          ['Turkey','Ankara','easy','https://en.wikipedia.org/wiki/Turkey'],
          ['Turkmenistan','Ashgabat','moderate','https://en.wikipedia.org/wiki/Turkmenistan'],
          ['Turks and Caicos','Cockburn Town','hard','https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands'],
          ['Tuvalu','Funafuti','hard','https://en.wikipedia.org/wiki/Tuvalu'],
          ['Uganda','Kampala','easy','https://en.wikipedia.org/wiki/Uganda'],
          ['Ukraine','Kiev','easy','https://en.wikipedia.org/wiki/Ukraine'],
          ['United Arab Emirates','Abu Dhabi','moderate','https://en.wikipedia.org/wiki/United_Arab_Emirates'],
          ['England','London','easy','https://en.wikipedia.org/wiki/England'],
          ['United States','Washington, D.C.','moderate','https://en.wikipedia.org/wiki/United_States'],
          ['United States Virgin Islands','Charlotte Amalie','hard','https://en.wikipedia.org/wiki/United_States_Virgin_Islands'],
          ['Uruguay','Montevideo','easy','https://en.wikipedia.org/wiki/Uruguay'],
          ['Uzbekistan','Tashkent','easy','https://en.wikipedia.org/wiki/Uzbekistan'],
          ['Vanuatu','Port Vila','hard','https://en.wikipedia.org/wiki/Vanuatu'],
          ['Vatican City','Vatican City','hard','https://en.wikipedia.org/wiki/Vatican_City'],
          ['Venezuela','Caracas','easy','https://en.wikipedia.org/wiki/Venezuela'],
          ['Vietnam','Hanoi','easy','https://en.wikipedia.org/wiki/Vietnam'],
          ['Wales','Cardiff','hard','https://en.wikipedia.org/wiki/Wales'],
          ['Wallis and Futuna','Mata-Utu','hard','https://en.wikipedia.org/wiki/Wallis_and_Futuna'],
          ['Western Sahara','El Aaiún','moderate','https://en.wikipedia.org/wiki/Western_Sahara'],
          ['Yemen','Sanaá','easy','https://en.wikipedia.org/wiki/Yemen'],
          ['Zambia','Lusaka','easy','https://en.wikipedia.org/wiki/Zambia'],
          ['Zimbabwe','Harare','easy','https://en.wikipedia.org/wiki/Zimbabwe']
        ];

        $timestamp = Carbon\Carbon::now();

        foreach ($countries as $country) {
          $difficulty = '';

          switch ($country[2]) {
            case 'easy':
            $difficulty = 1;
            break;

            case 'moderate':
            $difficulty = 2;
            break;

            case 'hard':
            $difficulty = 3;
              break;
          }

          Country::insert([
            'created_at' => $timestamp,
            'updated_at' => $timestamp,
            'name' => $country[0],
            'capital' => $country[1],
            'difficulty_level_id' => $difficulty,
            'wiki_link' => $country[3]
          ]);
        }
    }
}
